---
title: "clean_unsuper"
author: "Yun He"
date: "5/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer)
library(gplots)
library(tableone)
library(flextable)
library(magrittr)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## data cleaning
```{r}
heart_disease = read_csv("./data/heart.csv") %>% 
    mutate(target = ifelse(target == 1, "absence", "presence")) %>% 
    mutate(sex = as.factor(sex),
           cp = as.factor(cp),
           fbs = as.factor(fbs),
           restecg = as.factor(restecg),
           exang = as.factor(exang),
           slope = as.factor(slope),
           thal = as.factor(thal)
           )

set.seed(1)
trRows = createDataPartition(heart_disease$target, p = .75, list = FALSE)
train = heart_disease[trRows,]
test = heart_disease[-trRows,]

train.x <- model.matrix(target~.,train)[,-1]
train.y <- train$target


test.x <- model.matrix(target~.,test)[,-1]
test.y <- test$target
```

## EDA

### check missing value
```{r}
sapply(X = train, FUN = function(x) sum(is.na(x)))
```

### continuous
```{r}
train %>%
    select(age, trestbps, chol, thalach, oldpeak, target) %>% 
    gather(-target, key = "var", value = "value") %>% 
    ggplot(aes(x = target, y = value, fill = target)) +
    geom_boxplot(alpha = 0.5) +
    facet_wrap(~ var, scales = "free") +
    theme_bw()

train %>%
    select(age, trestbps, chol, thalach, oldpeak, target) %>% 
    gather(-target, key = "var", value = "value") %>% 
    ggplot(aes(x = value, fill = target)) +
    geom_density(alpha = 0.5) +
    facet_wrap(~ var, scales = "free") +
    theme_bw()
```

### corr matrix
```{r}
library(ggcorrplot)
train_continu = train %>%
    select(age, trestbps, chol, thalach, oldpeak)
corr =  round(cor(train_continu), 4)

ggcorrplot(corr, hc.order = TRUE, type = "lower",
   outline.col = "white",
   ggtheme = ggplot2::theme_bw,
   lab = T,
   colors = c("#6D9EC1", "white", "#E46726"))  
```

### categorical
```{r}
barplot = function(var){
    ggplot(train, aes_string(x = var,  group = "target")) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..)),
             stat = "count", alpha = 0.5) +
    geom_text(aes( label = scales::percent(..prop..),
                   y = ..prop.. ), 
              stat = "count", vjust = 0, size = 2) +
    labs(y = "Percent", fill = var) +
    facet_grid(~target) +
    scale_y_continuous(labels = scales::percent) +
        theme_bw()
}

a1 = barplot("sex")
a2 = barplot("fbs")
a3 = barplot("exang")
a4 = barplot("slope")
a5 = barplot("thal")
a6 = barplot("restecg")
a7 = barplot("cp")
a8 = barplot("ca")

gridExtra::grid.arrange(a1, a2, a3, a4,
                        a5, a6, a7, a8,
                        ncol = 3, nrow = 3)
```

## tableone

```{r}
vars = names(train)[-14]
tableOne = CreateTableOne(vars = c("age", "trestbps", "chol", "thalach",
                                   "oldpeak", "sex", "exang", "fbs", 
                                   "slope", "thal", "restecg", "cp","ca"
                                   ), 
                          strata = c("target"), 
                          data = train,
                          factorVars = c("sex", "fbs", "exang", "slope",
                                         "thal", "restecg", "cp", "ca"))
table = print(tableOne, cramVars = c("sex", "exang", "fbs"))
table = as.data.frame(table)

table = table %>% 
    mutate(name = rownames(table)) %>% 
    select(name, everything())


library(officer)
library(flextable)
mydoc <- read_docx() 
mydoc = mydoc %>% 
    body_add_flextable(flextable(table))

print(mydoc, target = "./table.docx")
    
```


## Unsupervised learning

## K-means
```{r}
set.seed(1)

train.x_scale = scale(train.x)

rownames(train.x_scale) = paste(train$target, 1:228, sep = "-")


km = kmeans(train.x_scale, centers = 2, nstart = 20)
km_vis = fviz_cluster(list(data = train.x_scale, 
                            cluster = km$cluster),
                       ellipse.type = "convex",
                       geom = c("point","text"),
                       labelsize = 5,palette = "Dark2") + 
    labs(title = "K-means")

km_vis
```

```{r}
train_kmeans = train
train_kmeans$kmean = km$cluster
train_kmeans %>% ggplot(aes(x = target, fill = target)) +
    geom_bar(alpha = 0.5) +
    facet_grid(.~kmean) +
    theme_bw()


center = t(apply(km$centers, 1, function(r)r*attr(train.x_scale,'scaled:scale') + attr(train.x_scale, 'scaled:center')))

center
```

## PCA
```{r}
train.x = scale(train.x)
pca <- prcomp(train.x)
fviz_eig(pca, addlabels = TRUE)
fviz_pca_ind(pca,
             habillage = train.y,
             label = "none",
             addEllipses = TRUE)
```


## Hierarchical clustering
```{r}
train_1 = train %>% 
    mutate(target = ifelse(target == "absence",1,0))
train.hc = train.x %>% as.data.frame() %>% 
    mutate(target = as.character(train_1$target),
           num =as.character(1:228)) %>% 
    mutate(name = paste(target,".", num)) %>% 
    select(-num, -target) %>% 
    column_to_rownames(var = "name") %>% scale()
    
```

```{r}

hc.heart = hclust(dist(train.hc), method = "complete")


fviz_dend(hc.heart, k = 4,
          cex = 0.4,
          palette = "jco",
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 0.8)
```

```{r}
col1 <- colorRampPalette(brewer.pal(9, "GnBu"))(100)

heatmap.2(t(train.hc),
        col = col1, keysize = 1, key.par = list(cex = .3),
        cexRow = 1, 
        #dendrogram = "col",
        trace = "none", key = TRUE, cexCol = 0.4,
        margins = c(5, 5))
```