---
title: "dsII_Holly"
author: "Yun He"
date: "5/14/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(caret)
library(factoextra)
library(e1071)
library(pROC)
```

## data cleaning
```{r}
heart_disease = read_csv("./data/heart.csv") %>% 
    mutate(target=ifelse(target==1, "neg", "pos"))
set.seed(1)
trRows = createDataPartition(heart_disease$target, p = .75, list = FALSE)
train = heart_disease[trRows,]
test = heart_disease[-trRows,]

train = train %>% 
    mutate(sex=as.factor(sex),
           cp=as.factor(cp),
           fbs=as.factor(fbs),
           restecg=as.factor(restecg),
           exang=as.factor(exang),
           slope=as.factor(slope),
           thal=as.factor(thal))
train.x <- model.matrix(target~.,train)[,-1]
train.y <- train$target

test = test %>% 
    mutate(sex=as.factor(sex),
           cp=as.factor(cp),
           fbs=as.factor(fbs),
           restecg=as.factor(restecg),
           exang=as.factor(exang),
           slope=as.factor(slope),
           thal=as.factor(thal))
test.x <- model.matrix(target~.,test)[,-1]
test.y <- test$target
```

## PCA
```{r}
train.x = scale(train.x)
pca <- prcomp(train.x)
fviz_eig(pca, addlabels = TRUE)
fviz_pca_ind(pca,
             habillage = train.y,
             label = "none",
             addEllipses = TRUE)
```

## SVM
```{r}
train = train %>% mutate(target=as.factor(target))
test = test %>% mutate(target=as.factor(target))
## linear boundary
ctrl <- trainControl(method = "cv")

set.seed(1)
svml.fit <- train(target~., 
                  data = train, 
                  method = "svmLinear2",
                  preProcess = c("center", "scale"),
                  tuneGrid = data.frame(cost = exp(seq(-5,0,len=50))),
                  trControl = ctrl)

ggplot(svml.fit, highlight = TRUE)
svml.fit$bestTune

## radial kernel
svmr.grid <- expand.grid(C = exp(seq(-4,6,len=50)),
                         sigma = exp(seq(-10,-3,len=6)))
set.seed(1)             
svmr.fit <- train(target~., 
                  data = train,
                  method = "svmRadial",
                  preProcess = c("center", "scale"),
                  tuneGrid = svmr.grid,
                  trControl = ctrl)

ggplot(svmr.fit, highlight = TRUE)
svmr.fit$bestTune

resamp <- resamples(list(svmr = svmr.fit, 
                         svml = svml.fit))
bwplot(resamp)
summary(resamp)
```

## Neural network
```{r}
nnetGrid <- expand.grid(size = seq(from = 1, to = 10, by = 1), 
                        decay = exp(seq(from = -3, to = 3, length = 30)))

ctrl2 <- trainControl(method = "cv", 
                      summaryFunction = twoClassSummary,
                      classProbs = TRUE)

set.seed(1)
cnnet.fit <- train(target~.,
                   train,
                   method = "nnet",
                   tuneGrid = nnetGrid,
                   preProcess = c("center","scale"),
                   trControl = ctrl2,
                   metric = "ROC",
                   trace = FALSE)

ggplot(cnnet.fit, highlight = TRUE) + scale_shape_manual(values = rep(19,10), 
                                                         guide = FALSE)
```


