---
title: "Untitled"
author: "JunLu"
date: "5/16/2019"
output: html_document
---

```{r}
library(ISLR)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer)
library(gplots)
library(tidyverse)
library(caret)
library(MLmetrics)
library(rpart.plot)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```


```{r}
heart_disease = read_csv("./data/heart.csv") %>% 
    mutate(target=ifelse(target==1, "absence", "presence"))
set.seed(1)
#trRows = createDataPartition(heart_disease$target, p = .75, list = FALSE)
#train = heart_disease[trRows,]
#test = heart_disease[-trRows,]

heart_disease = heart_disease %>% 
    mutate(sex=as.factor(sex),
           cp=as.factor(cp),
           fbs=as.factor(fbs),
           restecg=as.factor(restecg),
           exang=as.factor(exang),
           slope=as.factor(slope),
           thal=as.factor(thal))

model.x <- model.matrix(target~.,heart_disease)[,-1]
model.y <- heart_disease$target

```

