---
title: "haoran"
author: "Haoran Hu"
date: "2019-5-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ISLR)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer)
library(gplots)
library(tidyverse)
library(caret)
library(MLmetrics)
library(rpart.plot)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))

```

```{r}
heart_disease = read_csv("..\\data\\heart.csv")

set.seed(1)
trRows = createDataPartition(heart_disease$target, p = .75, list = FALSE)
train = heart_disease[trRows,]
test = heart_disease[-trRows,]

train = train %>% 
    mutate(cp=as.factor(cp),
           restecg=as.factor(restecg),
           slope=as.factor(slope),
           thal=as.factor(thal))
train.x <- model.matrix(target~.,train)[,-1]
train.y <- train$target

test = test %>% 
    mutate(cp=as.factor(cp),
           restecg=as.factor(restecg),
           slope=as.factor(slope),
           thal=as.factor(thal))
test.x <- model.matrix(target~.,test)[,-1]
test.y <- test$target
```


```{r}
train.hc = train.x %>% as.data.frame() %>% 
    mutate(target = as.character(train$target),
           num =as.character(1:228)) %>% 
    mutate(name = paste(target,".", num)) %>% 
    select(-num, -target) %>% 
    column_to_rownames(var = "name") %>% scale()
    
```


```{r}

hc.heart = hclust(dist(train.hc), method = "complete")


fviz_dend(hc.heart, k = 4,
          cex = 0.4,
          palette = "jco",
          color_labels_by_k = TRUE,
          rect = TRUE, rect_fill = TRUE, rect_border = "jco",
          labels_track_height = 0.8)
```

```{r}
col1 <- colorRampPalette(brewer.pal(9, "GnBu"))(100)

heatmap.2(t(train.hc),
        col = col1, keysize = 1, key.par = list(cex = .3),
        cexRow = 1, 
        #dendrogram = "col",
        trace = "none", key = TRUE, cexCol = 0.4,
        margins = c(5, 5))
```

##Tree

```{r}
ctrl = trainControl(method = "cv",
                    summaryFunction = twoClassSummary,
                    classProbs = TRUE)
train.y = as.factor(train.y) %>% 
    recode_factor("1" = "pos", "0" = "neg")

set.seed(1)
tree.class <- train(train.x, train.y,
                    method = "rpart",
                    tuneGrid = data.frame(cp = exp(seq(-10,-3, len = 20))),
                    trControl = ctrl,
                    metric = "ROC")
ggplot(tree.class, highlight = TRUE)
rpart.plot(tree.class$finalModel)
```

##Bagging

```{r}
bagging.grid <- expand.grid(mtry = 18,
                            splitrule = "gini",
                            min.node.size = 1:25)

set.seed(1)
bagging.class <- train(train.x, train.y,
                method = "ranger",
                tuneGrid = bagging.grid,
                metric = "ROC",
                trControl = ctrl,
                importance = "impurity")
ggplot(bagging.class, highlight = TRUE)

barplot(sort(ranger::importance(bagging.class$finalModel),
             decreasing = FALSE),
las = 2, horiz = TRUE, cex.names = 0.7,
col = colorRampPalette(colors = c("darkred","white","darkblue"))(18))
```

##Random Forest

```{r}
rf.grid <- expand.grid(mtry = 1:7,
                       splitrule = "gini",
                       min.node.size = seq(1,100, by = 2))

set.seed(1)
rf.class <- train(train.x, train.y,
                  method = "ranger",
                  tuneGrid = rf.grid,
                  metric = "ROC",
                  trControl = ctrl,
                  importance = "impurity")

ggplot(rf.class, highlight = TRUE) +
viridis::scale_color_viridis(
discrete = TRUE
) + scale_shape_manual(values = seq(1,7))

barplot(sort(ranger::importance(rf.class$finalModel), decreasing = FALSE),
las = 2, horiz = TRUE, cex.names = 0.7,
col = colorRampPalette(colors = c("darkred","white","darkblue"))(18))

```

##Boosting

```{r fig.height=12, fig.width=12}
boost.grid <- expand.grid(n.trees = seq(25, 1600, by = 25),
                          interaction.depth = 1:6,
                          shrinkage = c(0.019, 0.022, 0.025, 0.028, 
                                        0.031, 0.034, 0.037, 0.040),
                          n.minobsinnode = 1)

set.seed(1)
# Adaboost loss function
boost.class = train(train.x, train.y,
                    tuneGrid = boost.grid,
                    trControl = ctrl,
                    method = "gbm",
                    distribution = "adaboost",
                    metric = "ROC",
                    verbose = FALSE)

ggplot(boost.class, highlight = TRUE) +
viridis::scale_color_viridis(
discrete = TRUE
) + scale_shape_manual(values = seq(0,10))

summary(boost.class$finalModel, las = 2, cBars = 19, cex.names = 0.6)
```

```{r}
resamp = resamples(list(boost = boost.class, rf = rf.class, 
                        bagging = bagging.class, tree = tree.class))
summary(resamp)
bwplot(resamp, metric = "ROC")
```

